name: Snyk Generic Scan

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.3.3
      - name: pip install
        run: pip install -r src/requirements.txt
      - name: Snyk Install
        run: npm install snyk -g
      # - name: Snyk Auth
      #   run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk SCA Monitor
        run: snyk monitor --all-projects --org=9c1712cb-4430-4d28-b501-3555ea48f091
      - name: Snyk SCA Test
        run: snyk test --all-projects --severity-threshold=high
      - name: Snyk Code Test
        run: snyk code test --severity-threshold=high --org=9c1712cb-4430-4d28-b501-3555ea48f091
