name: Snyk Generic Scan

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: Snyk Install
        run: npm install snyk -g
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk SCA Monitor
        run: snyk monitor --all-projects --org=b0d049be-0911-4ce3-ad63-598a5b8ff1ef
      - name: Snyk SCA Test
        run: snyk test --all-projects --severity-threshold=high
      - name: Snyk Code Test
        run: snyk code test --severity-threshold=high --org=b0d049be-0911-4ce3-ad63-598a5b8ff1ef
